tap "thezoraiz/ascii-image-converter"
# Portable ASCII art graphics library
brew "aalib"
# Run your GitHub Actions locally
brew "act"
# ANSI HTML adapter
brew "aha"
# Strip or convert ANSI codes into HTML, (La)Tex, RTF, or BBCode
brew "ansifilter"
# General-purpose data compression with high compression ratio
brew "xz"
# ANSI/ASCII art to PNG converter
brew "ansilove"
# Record and share terminal sessions
brew "asciinema"
# Aquarium animation in ASCII art
brew "asciiquarium"
# ASCII-art image browser and animation viewer
brew "aview"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Draw boxes around text
brew "boxes"
# Versatile and fast Unicode/ASCII/ANSI graphics renderer
brew "chafa"
# Ruby environment tool
brew "chruby"
# Apjanke's fork of the classic cowsay project
brew "cowsay"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# Banner-like program prints strings as ASCII art
brew "figlet"
# Command-line outline and bitmap font editor/converter
brew "fontforge", link: false
# Infamous electronic fortune-cookie generator
brew "fortune"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Fast linters runner for Go
brew "golangci-lint"
# Golang security checker
brew "gosec"
# Image manipulation
brew "netpbm"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Configurable static site generator
brew "hugo"
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# Convert JPG images to ASCII
brew "jp2a"
# Convert pixel information into colored ASCII art
brew "libcaca"
# YAML Parser
brew "libyaml"
# Rainbows and unicorns in your console!
brew "lolcat"
# Clone of ls with colorful output, file type icons, and more
brew "lsd"
# Powerful, lightweight programming language
brew "lua"
# Package manager for the Lua programming language
brew "luarocks"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# POSIX *nix fetch script using Nerdfonts
brew "nerdfetch"
# Manage multiple Node.js versions
brew "nvm"
# Create, run, and share large language models (LLMs)
brew "ollama", restart_service: :changed
# Monitor data's progress through a pipe
brew "pv"
# Python version management
brew "pyenv"
# Pyenv plugin to manage virtualenv
brew "pyenv-virtualenv"
# Install Ruby, JRuby, Rubinius, TruffleRuby, or mruby
brew "ruby-install"
# State of the art linter for the Go programming language
brew "staticcheck"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Color-based alternative to figlet (uses libcaca)
brew "toilet"
# Convert images into ascii art
brew "thezoraiz/ascii-image-converter/ascii-image-converter"
