tap "homebrew/bundle"
tap "homebrew/services"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Ruby environment tool
brew "chruby"
# Apjanke's fork of the classic cowsay project
brew "cowsay"
# Banner-like program prints strings as ASCII art
brew "figlet"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Configurable static site generator
brew "hugo"
# YAML Parser
brew "libyaml"
# Rainbows and unicorns in your console!
brew "lolcat"
# Clone of ls with colorful output, file type icons, and more
brew "lsd"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# POSIX *nix fetch script using Nerdfonts
brew "nerdfetch"
# Manage multiple Node.js versions
brew "nvm"
# Create, run, and share large language models (LLMs)
brew "ollama", restart_service: :changed
# Python version management
brew "pyenv"
# Pyenv plugin to manage virtualenv
brew "pyenv-virtualenv"
# General-purpose data compression with high compression ratio
brew "xz"
# Install Ruby, JRuby, Rubinius, TruffleRuby, or mruby
brew "ruby-install"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
